name: "Quarto Extensions Update"
description: "Run `quarto update` for CRIT course extensions."
runs:
  using: "composite"
  steps:
    - name: Setup Quarto
      uses: quarto-dev/quarto-actions/setup@v2
    
    - name: Run extension updates
      run: |
        set -euo pipefail
        quarto update --no-prompt mcanouil/quarto-iconify
        quarto update --no-prompt quarto-ext/fontawesome
        quarto update --no-prompt tavareshugo/crit-quarto-ext/callout-exercise
        quarto update --no-prompt tavareshugo/crit-quarto-ext/crit-format
        quarto update --no-prompt tavareshugo/crit-quarto-ext/citation-cff-parser
      shell: bash
