name: Quarto book archive release

on:
  workflow_call:
    inputs:
      pre_render:
        required: false
        type: string
      post_render:
        required: false
        type: string

jobs:
  create-archive:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout tagged commit
      uses: actions/checkout@v4
      with:
        ref: ${{ github.ref }}

    - name: Extract tag name
      id: tag
      run: |
        TAG_NAME=${GITHUB_REF#refs/tags/}
        echo "tag_name=$TAG_NAME" >> $GITHUB_OUTPUT
        echo "Detected tag: $TAG_NAME"

    - name: Setup Quarto
      uses: quarto-dev/quarto-actions/setup@v2

    - name: Optional pre-render commands
      if: ${{ inputs.pre_render != '' }}
      run: ${{ inputs.pre_render }}

    - name: Render tagged version
      run: quarto render

    - name: Optional post-render commands
      if: ${{ inputs.post_render != '' }}
      run: ${{ inputs.post_render }}

    - name: Prepare archive directory
      run: |
        mv _site ${{ steps.tag.outputs.tag_name }}
        echo "Archive directory created: ${{ steps.tag.outputs.tag_name }}"

    - name: Checkout gh-pages branch
      uses: actions/checkout@v4
      with:
        ref: gh-pages
        path: _site

    - name: Setup archive structure
      run: |
        mkdir -p _site/archive
        cp -r ${{ steps.tag.outputs.tag_name }} _site/archive/
        echo "Archive contents:"
        ls -la _site/archive/

    - name: Publish
      uses: JamesIves/github-pages-deploy-action@4.1.0
      with:
        branch: gh-pages
        folder: _site
        single-commit: true
